### ISSUE TITLE
Odd data_extract_spec behaviour

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.transform#117]
I'm running the roxygen example of tm_t_tte (on main) in tmc and it has:

```
paramcd = choices_selected(
  value_choices(ADTTE, "PARAMCD", "PARAM"),
  "OS"
),
```

And when I load the app it  does have "OS" selected but then immediately replaces it with CRSD (the first option in the dropdown list)

Does anyone know why? Is this behaviour widespread? Do we care?

I suspect it's something buried deep in teal.transform (I mention because when the original "OS" is selected the shinyvalidate messages aren't happy (though after the initial load is completed they then behave correctly) - interestingly the first pass through (with OS) correctly shows the column labels (OS 'Overall Survival') but then when it overwrites to CRSD it doesn't...

Transfer to tmc if that makes sense

**Comment by gogonzo** [comment]
I confirm, `data_extract_filter_srv` gets the `filter_spec` with `selected = NULL`. Somewhere in between `selected` is erased

test app
```r
pkgload::load_all("teal.data")
pkgload::load_all("teal.transform")
#> Loading required package: magrittr
library(shiny)

extract_ui <- function(id, data_extract) {
  ns <- NS(id)
  teal.widgets::standard_layout(
    output = teal.widgets::white_small_well(verbatimTextOutput(ns("output"))),
    encoding = data_extract_ui(ns("data_extract"), label = "variable", data_extract)
  )
}

extract_srv <- function(id, data, data_extract) {
  moduleServer(id, function(input, output, session) {
    reactive_extract_input <- data_extract_srv("data_extract", data, data_extract, join_keys = attr(data, "join_keys"))

    merged <- merge_expression_srv(selector_list = reactive(list(x = reactive_extract_input)), datasets = data, join_keys = attr(data, "join_keys"))
    s <- reactive(merged()$expr)
    output$output <- renderPrint(s())
  })
}

tm_extract <- function(label = "extract", data_extract) {
  teal::module(
    label = label,
    server = extract_srv,
    ui = extract_ui,
    server_args = list(data_extract = data_extract),
    ui_args = list(data_extract = data_extract)
  )
}

# Define data.frame objects
ADSL <- scda::synthetic_cdisc_data("latest")$adsl # nolint
ADTTE <- scda::synthetic_cdisc_data("latest")$adtte # nolint

# create a list of data.frame objects
data <- cdisc_data(
  cdisc_dataset("ADSL", ADSL),
  cdisc_dataset("ADTTE", ADTTE)
)

app <- teal::init(
  data = data,
  modules = list(
    tm_extract(
      "extract-4",
      data_extract_spec(
        dataname = "ADTTE",
        filter = filter_spec(
          vars = "PARAMCD",
          value_choices(ADTTE, "PARAMCD", "PARAM"), 
          "OS"
        )
      )
    )
  )
)

runApp(app)

```

**Comment by nikolas-burkoff** [comment]
So this is the code that overwrites it is [here](https://github.com/insightsengineering/teal.transform/blob/main/R/data_extract_filter_module.R#L75-L89)

It gets called on the 2nd call to updateOptionalSelectInput [here](https://github.com/insightsengineering/teal.transform/blob/main/R/data_extract_filter_module.R#L101) (the first is [here]( https://github.com/insightsengineering/teal.transform/blob/main/R/data_extract_filter_module.R#L95))

If I comment out the two `updateOptionalSelectInput` then the example above works fine. @pawelru @gogonzo I do not understand this part of the code base - I assume something terrible will happen if I do that?

**Comment by mhallal1** [comment]
> data_extract_filter_srv

The two `updateOptionalSelectInput` are still needed when the `data_extract_spec` is not selected by default, the user then selects the variable but the levels of the variable do not get updated, have a look at the example of `tm_g_distribution` in tmg to understand the case.
