### ISSUE TITLE
data extract filter module removing variable labels

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal.transform#120]
I noticed this when I was reviewing #119.

In `data_extract_filter_srv` the `vals` input is initialized as `var label` (e.g. `OS Overall Survival`). However, shortly after app load the labels get dropped so we just have `var` (`OS`).

The problem appears to be in [this block](https://github.com/insightsengineering/teal.transform/blob/cb6241ac184667063f72ebe4e058dcaa5f635161/R/data_extract_filter_module.R#L75-L82) where choices is overwritten. The logical conditions in the `observeEvent` that [calls this code](https://github.com/insightsengineering/teal.transform/blob/cb6241ac184667063f72ebe4e058dcaa5f635161/R/data_extract_filter_module.R#L67) don't quite make sense to me as it's not entirely clear they are mutually exclusive cases.

Is the correct behavior to display the labels along with the variable?

Example app

```r
pkgload::load_all("teal.data")
pkgload::load_all("teal.transform")
#> Loading required package: magrittr
library(shiny)

extract_ui <- function(id, data_extract) {
    ns <- NS(id)
    teal.widgets::standard_layout(
        output = teal.widgets::white_small_well(verbatimTextOutput(ns("output"))),
        encoding = data_extract_ui(ns("data_extract"), label = "variable", data_extract)
    )
}

extract_srv <- function(id, data, data_extract) {
    moduleServer(id, function(input, output, session) {
        reactive_extract_input <- data_extract_srv("data_extract", data, data_extract, join_keys = attr(data, "join_keys"))
        merged <- merge_expression_srv(selector_list = reactive(list(x = reactive_extract_input)), datasets = data, join_keys = attr(data, "join_keys"))
        s <- reactive(merged()$expr)
        output$output <- renderPrint(s())
    })
}

tm_extract <- function(label = "extract", data_extract) {
    teal::module(
        label = label,
        server = extract_srv,
        ui = extract_ui,
        server_args = list(data_extract = data_extract),
        ui_args = list(data_extract = data_extract)
    )
}

# Define data.frame objects
ADSL <- scda::synthetic_cdisc_data("latest")$adsl # nolint
ADTTE <- scda::synthetic_cdisc_data("latest")$adtte # nolint

# create a list of data.frame objects
data <- cdisc_data(
    cdisc_dataset("ADSL", ADSL),
    cdisc_dataset("ADTTE", ADTTE)
)

app <- teal::init(
    data = data,
    modules = list(
        tm_extract(
            "extract-4",
            data_extract_spec(
                dataname = "ADTTE",
                filter = filter_spec(
                    vars = "PARAMCD",
                    value_choices(ADTTE, "PARAMCD", "PARAM"),
                    "OS"
                )
            )
        )
    )
)

runApp(app)
```

On load:

![image](https://user-images.githubusercontent.com/36482959/210013384-3c62848d-2449-4e39-be7d-00176ab41079.png)

Just after load:

![image](https://user-images.githubusercontent.com/36482959/210013539-16f9d99c-b6ce-466e-863a-1ed09791aaa2.png)

**Comment by gogonzo** [comment]
closed in #121
