### ISSUE TITLE
Review `teal.transform` documentation before release

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.transform#125]
### Summary
Related with insightsengineering/nestdevs-tasks#13
In preparation to release, we need to review/assess all documentation in the package. 

### Acceptance Criteria
* Review roxygen examples on all functions
  * Test examples
  * If it's using chunk, update to `qenv`.
* Review vignettes on these topics only:
  * Review any content around `qenv`
  * Review any content around `chunks` (i.e. make sure the right language around deprecation)
  * Review any content around shinyvalidate
* Update NEWS
* Update README (if applicable)
* Review DESCRIPTION file (i.e. dependency versions, etc)

**Comment by asbates** [comment]
Current status: working through running examples.

**Comment by asbates** [comment]
status: all examples have been checked and/or fixed.
