### ISSUE TITLE
Branches cleanup

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.transform#135]
### What is your question?

Hey @cicdguy what you think about branches cleanup? Should we removed closed and merged branches? There are 4 out of 8 that I think could be removed to simplify the overview of the repo
![image](https://github.com/insightsengineering/teal.transform/assets/133694481/d4876b1d-eeb7-4412-9cf1-5222e27d8511)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
Understoond @cicdguy  . Would you like to take honors and deleted closed branches?

**Comment by m7pr** [comment]
@cicdguy should be start any recurring issues to get branches cleaned up? Like once a month?

**Comment by donyunardi** [comment]
Hi @m7pr 
Can we close this?
