### ISSUE TITLE
Should we remove rADAE and rADLB datasets as they are only used in tests?

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.transform#141]
### What is your question?

Currently we have 5 dataset in teal.transform. Should 2 of them (rADAE and rADLB) be removed as they are used only in tests?
cc @gogonzo @kartikeyakirar 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gogonzo** [comment]
Theoretically teal.transform tests and examples could work fine with two or three datasets only - but I know there are thousands of lines in tests written for these (five) datasets. I'm fine with keeping them all at this moment. This package will be refactored someday so I'm fine with 5 datasets also.

**Comment by m7pr** [comment]
cool, let's keep 5
