### ISSUE TITLE
Remove data_merge_module and data_merge_srv in next release afrer 0.3.1

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.transform#144]
### Feature description

Follow-up after https://github.com/insightsengineering/teal.transform/pull/143
`data_merge_module()` and `data_merge_srv()` were deprecated with the stop error message. They were left exported only to throw an error on the usage of those functions. Those two should be removed in the released that comes after 0.3.1 release.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
### Acceptance Criteria
* Removal of deprecated function
* Check if vignettes needs to be updated across all teal framework
* Update NEWS.md

**Comment by gogonzo** [comment]
implemented on the feature branch
