### ISSUE TITLE
[Question]: Move `magrittr` to from Depends to Imports and re-export `%>%`?

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/teal.transform#179]
### What is your question?

Should we move this dependency to Imports?

It might be tight for the release to CRAN, but if not this should be done in the refactor of the package.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by pawelru** [comment]
Even better: remove magrittr and re-export [from `dplyr`](https://github.com/tidyverse/dplyr/blob/b359331a448a693546d77245b0de4d405bab3886/NAMESPACE#L184)
