### ISSUE TITLE
Descriptive error message

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.transform#99]
Please provide a more descriptive error message here:

https://github.com/insightsengineering/teal.transform/blob/ad28584f5e73c2859b71e085a6b0be933fcdb6a6/R/choices_labeled.R#L211

tagging @sgorm123

**Comment by asbates** [comment]
@donyunardi Do you think we should open another issue(s) for the rest of the package? I think any other place that uses `stopifnot()` will have uninformative error messages as well.

**Comment by donyunardi** [comment]
Good idea. 
It looks like we have quite a number of `stopifnot()` being used.
Let's bring this up for a discussion for better execution plan.

**Comment by asbates** [comment]
@donyunardi The affected file here `R/choices_labeled.R` is repeated in [`teal.slice`](https://github.com/insightsengineering/teal.slice/blob/main/R/choices_labeled.R). We could make the same changes here (#102) in `teal.slice` but that seems like a temporary solution at best. I've opened insightsengineering/teal.slice/issues/120 to address this.


For now though, what do you recommend we do here?

**Comment by donyunardi** [comment]
Thanks for catching this and creating the issue.
Not sure if there's a reason behind this and it would be better to huddle up with the team to execute this efficiently.
I'd say we move forward with current PR so we can address and resolve initial report, and strategize our next move, including the case of teal.slice.
